name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [11, 17]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      

